version: '3.4'

services:

  grpclab-api-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LogMultiline=true
      - IdentityUrl=http://grpclab-identity-service
      - AuthKey=Bearer

  grpclab-identity-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LogMultiline=true
      - CertPath=/certs/certificate.pfx
      - CertPass=123456
      - EventBusConnection=rabbitmq
      - EventBusUserName=user
      - EventBusPassword=P@ssword1
      - SubscriptionClientName=Identity

  grpclab-contact-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CertPath=/certs/certificate.pfx
      - CertPass=123456
      - ProfileUrl=https://grpclab-profile-serivce
      - EventBusConnection=rabbitmq
      - EventBusUserName=user
      - EventBusPassword=P@ssword1
      - SubscriptionClientName=Contact

  grpclab-profile-serivce:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CertPath=/certs/certificate.pfx
      - CertPass=123456
      - EventBusConnection=rabbitmq
      - EventBusUserName=user
      - EventBusPassword=P@ssword1
      - SubscriptionClientName=Profile

  grpclab-proxy:
    environment:
      - Updated=2